CREATE DATABASE CRM;

CREATE TABLE SETOR(
    STRCODIGO INT PRIMARY KEY AUTO_INCREMENT,
    STRNOME VARCHAR(50) NOT NULL
);

CREATE TABLE ANALISTA(
    ANLMATRICULA INT PRIMARY KEY AUTO_INCREMENT,
    ANLNOME VARCHAR(150) NOT NULL,
    ANLSENHA VARCHAR(20) NOT NULL,
    ANLEMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE ESTADO(
    ESTSIGLA CHAR(2) PRIMARY KEY,
    ESTNOME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE CIDADE(
    CDDCODIGO INT PRIMARY KEY AUTO_INCREMENT,
    CDDNOME VARCHAR(50) NOT NULL,
    CDDESTADO CHAR(2) NOT NULL,
    CONSTRAINT FOREIGN KEY(CDDESTADO) REFERENCES ESTADO(ESTSIGLA)
);

CREATE TABLE ENDERECO(
    ENDCEP CHAR(8) PRIMARY KEY,
    ENDCIDADE INT NOT NULL,
    ENDESTADO CHAR(2) NOT NULL,
    CONSTRAINT FOREIGN KEY(ENDCIDADE) REFERENCES CIDADE(CDDCODIGO),
    CONSTRAINT FOREIGN KEY(ENDESTADO) REFERENCES ESTADO(ESTSIGLA)
);

CREATE TABLE GRUPO(
    GRPCODIGO INT PRIMARY KEY,
    GRPNOME VARCHAR(50) NOT NULL
);